### ISSUE TITLE
在Windows2012下无法运行

### ISSUE THREAD

**Issue by ShiaBox** [rhwong/unidbg-fetch-qsign-onekey#1]
会直接乱码，2008也是。
希望可以修正。

**Comment by rhwong** [comment]
copy来的源码，不会修，摆烂了，有机会重写
请直接下载压缩包。

**Comment by kagangtuya-star** [comment]
bat文件转换一下编码格式即可
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/73411104/0c931772-978d-4707-89b1-e9ebe16d7b9c)
