### ISSUE TITLE
[2023-08-02 09:19:47] [WARNING]: lambda 初始化失败: Post "http:///runtime/init/ready": http: no Host in request URL

### ISSUE THREAD

**Issue by yufengya0420** [rhwong/unidbg-fetch-qsign-onekey#11]
[2023-08-02 09:19:47] [WARNING]: lambda 初始化失败: Post "http:///runtime/init/ready": http: no Host in request URL
这个提示不影响什么吧

**Comment by rhwong** [comment]
这个是哪里的回复。。？

**Comment by yufengya0420** [comment]
> 这个是哪里的报错。。？ go-cqhttp的吗

go-cqhttp的

**Comment by yufengya0420** [comment]
> 不清楚，如果能用就没啥影响。 看起来是gocq那边的数据库读写。

我改了一下gocq的配置文件就好了，里面有个ws正向地址需要手动编辑
