### ISSUE TITLE
系统错误 找不到jli.dll

### ISSUE THREAD

**Issue by yufengya0420** [rhwong/unidbg-fetch-qsign-onekey#13]
系统错误 找不到jli.dll
![Snipaste_2023-08-09_22-03-06](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/99462074/6cb9825d-7d47-4776-80af-4f1cebea4948)

**Comment by yufengya0420** [comment]
打开Start_Qsign.bat时报错的

**Comment by rhwong** [comment]
检查是否有杀软等，删除了\jre\bin\jli.dll
这是java的组件，如果您删除了它当然无法运行。

**Comment by yufengya0420** [comment]
> 检查是否有杀软等，删除了\jre\bin\jli.dll 这是java的组件，如果您删除了它当然无法运行。

需要Java的哪个版本？我重装一下Java

**Comment by yufengya0420** [comment]
重装了Java17并没有用

**Comment by yufengya0420** [comment]
![Uploading image.png…]()
明明就有但是提示缺少

**Comment by yufengya0420** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/99462074/84c4d8a1-3a83-4d16-bba2-cddabc5efd29)

**Comment by yufengya0420** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/99462074/88d43e85-9a60-476d-a114-b0ec8c75adb0)

**Comment by rhwong** [comment]
但是报的提示就是这个意思。
尝试缩短文件夹名称路径。
另外你是不是手动运行的而没使用脚本运行？？

**Comment by rhwong** [comment]
Close: 原因不明，可能是杀软问题。
