### ISSUE TITLE
[bug]：dial tcp 127.0.0.1:13579: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Baymacf** [rhwong/unidbg-fetch-qsign-onekey#14]
我使用windows server 2019进行搭建，并且选择了repo版的gocq。但是在bot被风控我再次重启gocq时发生了如下报错，并且在我重新安装了gocq与签名服务器之后仍然不行。请问这是什么原因呢？我感觉似乎是签名服务器的服务没有开启导致连接失败了。
报错截图如下：
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/128383518/751cbdec-78d6-446e-a48f-c74da19deb0c)

**Comment by Baymacf** [comment]
选择其他的搭建方式是不是会更好一些呢？多谢指点！

**Comment by rhwong** [comment]
检查签名服务器端是否正常
建议重启签名服务器
若重启没有解决的话，建议删除`txlib_version.json`，以重新设置签名服务。
再次设置时，请将`host`设置为`0.0.0.0`

**Comment by Baymacf** [comment]
多谢！重新设置一遍解决了，似乎是因为我把命令行关闭了导致签名服务完全没有开启（捂脸），但之前我一直是这样跑的。总之问题解决了，多谢您！！
