### ISSUE TITLE
登入失败

### ISSUE THREAD

**Issue by QwindF** [rhwong/unidbg-fetch-qsign-onekey#17]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/87116340/4b7c2335-ee18-4b63-b1fa-6b36d658b31e)
最新版本
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/87116340/473736b6-dfd0-45c2-bfe3-8718b32f52dd)
同目录运行，
windows11
之前用1.1.0用了挺长时间了，然后给风控+登入失败就跟新了

**Comment by rhwong** [comment]
Wrong API key
这不是写的很清楚了。

**Comment by QwindF** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/87116340/111bba15-7436-4417-ac90-189cf9c34337)

**Comment by QwindF** [comment]
key输入在哪里，

**Comment by rhwong** [comment]
你得重新生成config
