### ISSUE TITLE
cqhttp登录账号后闪退

### ISSUE THREAD

**Issue by 2331892928** [rhwong/unidbg-fetch-qsign-onekey#18]
qsign版本：1.1.9
qsign qq版本：8.9.68
go cqhttp版本：从此项目下载，下载时间：20230826,从Release下载 名称：[unidbg-fetch-qsign-onekey-1.1.9-go-cqhttp-x86.zip](https://github.com/rhwong/unidbg-fetch-qsign-onekey/releases/download/onekey/unidbg-fetch-qsign-onekey-1.1.9-go-cqhttp-x86.zip)
go cqhttp qq设备版本：8.9.68
qsign日志：
[FEKit_]info: qq_sign.h:142 [GetSign] cmd:wtlogin.exchange_emp
FEBound.transform(111a0103000000000200030000ea0b0b8996d62ebcd45715f6e842efa8fd2cecac000000004865726f) => a15955f1a8520da7560dbb530da56009b381ab65c1b98b7b3e65300c9e44ef837ba752fda80deed54b
[FEKit_]info: qq_sign.h:142 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
FEBound.transform(3444e84777d0e7f5c5f501030000000002000300008250500fedab7964e9d356fd000000004865726f) => 4e93c87e17b21b2bd3fabd560db8630dfda759fda81c8d675b69d5fd33ac342b82a752fda80deed54b
[FEKit_]info: ChannelManager.cpp:98 origin cmd:GetSecConf ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:101 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:GetSecConf
[FEKit_]info: task_handle.h:76 TaskSystem not allow
[FEKit_]info: task_handle.h:76 TaskSystem not allow
[FEKit_]info: qq_sign.h:142 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
FEBound.transform(3062e852b2d0867d7df70103000000000000030000aff0a030ea9c536032f5c5f5000000004865726f) => 4c72c820c4b257d1fff0bd560db8630dfca759fda89e6d37c2669e663d5d087489a752fda80deed54b
[FEKit_]info: ChannelManager.cpp:98 origin cmd:O3GetTail ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:101 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:O3GetTail
[FEKit_]info: task_handle.h:76 TaskSystem not allow
[FEKit_]error: sign_tail_manager.h:79 get tail success 1, retCode 0
FEBound.transform(fb64dea6bfa11285e5d20115904289fd2eb16843ffdc2a73ca7975673e641c31) => 8773a634cb97b0eb7387bd352d3d9a9cd0fb78714bb092ddd4e2511ef2672fe5
[FEKit_]error: ChannelManager.cpp:73 o3cm@S: O3ReportTail, trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access
uin = 1186431337, id = 3, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access, data = 0a0c4f335265706f72745461696c1222a8bb8a1d95d65a17e09c2bdeb835d18c15c41509610feac33ed6c21c9c54173e00871a20ec85f89f612ba042967ff7284e9251c480a0649ae672b46793bbc8eb56b34054)
[FEKit_]info: qq_sign.h:142 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
FEBound.transform(408b45cb6c8a8d64ca1c58d6d68e28e8a0680103000000000000030000e85a21280000000029d0c774) => 0cb64f13f1165894d4ce0aea5a19eb8e7c7055f1a8520da7520dbb530dab1c65d5a752fda8cb2dbaf1
[FEKit_]info: qq_sign.h:142 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access
FEBound.transform(42837b0d4e56ba6877dc0103000000000000030000e2fdddfd49e3e3c7e85ea5680000000029d0c774) => 0dbe84f99924f298fa8ebd560db8630dfca759fda88c68c13fa2cb06d0ab16a435a752fda8cb2dbaf1
[FEKit_]info: ChannelManager.cpp:98 origin cmd:getToken ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:101 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:getToken
[FEKit_]info: task_handle.h:76 TaskSystem not allow
[FEKit_]info: device_token.h:274 response len :20
[FEKit_]info: device_token.h:297 DeviceToken::saveToken ok! expireTime:1693209356

go cqhttp info日志
[2023-08-27 16:01:52] [INFO]: submit sign: uin=1186431337, cmd=trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, callbackID=0, buffer=[10 135 2 227 175 135 71 94 195 252 41 169 153 115 29 163 207 162 126 184 19 95 19 93 43 94 169 147 168 60 227 171 112 117 63 141 64 66 104 45 104 88 111 157 209 139 95 50 131 217 29 201 96 140 168 18 88 21 46 111 237 73 51 69]... 
[2023-08-27 16:01:53] [INFO]: submit sign: uin=1186431337, cmd=trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, callbackID=1, buffer=[10 134 1 75 172 95 40 69 220 207 235 2 128 83 153 159 64 94 12 32 42 100 29 164 14 47 213 178 189 195 26 235 217 180 157 121 195 132 20 201 166 48 100 109 114 82 146 7 139 52 139 7 133 170 3 26 29 46 239 77 27 212 138 52]... 
[2023-08-27 16:01:53] [INFO]: submit sign: uin=1186431337, cmd=trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, callbackID=2, buffer=[10 148 1 176 134 229 130 51 0 113 121 204 244 127 188 140 154 237 111 227 62 172 28 207 59 47 210 177 133 153 5 68 166 32 14 82 180 245 177 250 107 183 157 7 161 254 31 78 150 225 253 143 40 136 135 70 5 238 216 47 252 77 63 44]...

**Comment by 2331892928** [comment]
qsign没闪退，go cqhttp 闪退，日志如上

**Comment by 2331892928** [comment]
8.9.63就可以运行，但有个error：[2023-08-27 16:09:18] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005

**Comment by rhwong** [comment]
go-cqhttp日志提供一下

**Comment by 2510206409** [comment]
> go-cqhttp日志提供一下

![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/25257418/dd513a4a-baf3-49f3-8feb-aa5bdecb824c)

**Comment by rhwong** [comment]
> parse incoming packet error: return code unsuccessful: -10005

parse incoming packet error: return code unsuccessful: -10005这个问题如果不影响使用则可以无视
目前go-cqhttp当前的actions尚存在问题，登录完成后的一段时间，刷新token会失败。
我一直在跟最新版的实机测试，然后会将测试正常的go-cqhttp更新到当前仓库。

**Comment by komomon** [comment]
> > parse incoming packet error: return code unsuccessful: -10005
> 
> parse incoming packet error: return code unsuccessful: -10005这个问题如果不影响使用则可以无视 目前go-cqhttp当前的actions尚存在问题，登录完成后的一段时间，刷新token会失败。 我一直在跟最新版的实机测试，然后会将测试正常的go-cqhttp更新到当前仓库。

并没有登录成功，发消息也没有响应

**Comment by rhwong** [comment]
> > > parse incoming packet error: return code unsuccessful: -10005
> > 
> > 
> > parse incoming packet error: return code unsuccessful: -10005这个问题如果不影响使用则可以无视 目前go-cqhttp当前的actions尚存在问题，登录完成后的一段时间，刷新token会失败。 我一直在跟最新版的实机测试，然后会将测试正常的go-cqhttp更新到当前仓库。
> 
> 并没有登录成功，发消息也没有响应

说的是能登陆成功的情况下出现这个报错

**Comment by rhwong** [comment]
无进一步反馈
