### ISSUE TITLE
这玩意部署完之后怎么让别人也用？

### ISSUE THREAD

**Issue by Anzu0831** [rhwong/unidbg-fetch-qsign-onekey#2]
在服务器上部署了这个之后，试着用本地goc去用这个qsign，config里写的http://(云服务器的外网IP):13579。服务器的android_id和本地这个goc的android_id是一致的。

**Comment by rhwong** [comment]
部署时，地址使用0.0.0.0
然后云服务器需要去运营商的面板处开放防火墙端口
