### ISSUE TITLE
Start_Qsign.bat打开闪退

### ISSUE THREAD

**Issue by yufengya0420** [rhwong/unidbg-fetch-qsign-onekey#20]
Start_Qsign.bat打开闪退
已经安装了Java17

**Comment by yufengya0420** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/99462074/5e66483a-530f-421e-8389-ea2622e95fc3)
sign-server和key填完之后打开Start_Qsign.bat就闪退，然后填的就白填了

**Comment by rhwong** [comment]
脚本不会检测你本地的JAVA，只会调用目录里自带的OPENJDK11。
sign-server和key不需要你填写，脚本会帮你填写。
如果你不希望由脚本托管sign-server和key（例如适配最新的多签名服务器dev），那么请分开目录运行。
