### ISSUE TITLE
运行Start_Qsign.bat后，cmd窗口闪一下就没了

### ISSUE THREAD

**Issue by Arnolwutong** [rhwong/unidbg-fetch-qsign-onekey#21]
运行Start_Qsign.bat后，cmd窗口闪一下就没了。
下载了unidbg-fetch-qsign-onekey-1.1.6-go-cqhttp-x86.zip和unidbg-fetch-qsign-onekey-1.1.9-go-cqhttp-x86.zip。
这两个都是同样的问题。
解压运行Start_Qsign.bat，全部回车默认配置。cmd窗口闪一下就没了。

**Comment by Arnolwutong** [comment]
![运行Start_Qsign bat后，cmd窗口闪一下就没了。](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/95761056/c132ebc9-ac41-44fa-b765-85c1df033032)

**Comment by Arnolwutong** [comment]
![运行Start_Qsign bat后，cmd窗口闪一下就没了。](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/95761056/81ac7115-7d4d-4a51-80a9-91e1301b2063)

**Comment by Arnolwutong** [comment]
![VeryCapture_20230905091208](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/95761056/b86dc778-2906-4b89-92c6-9de0fbcfcb16)

**Comment by rhwong** [comment]
尝试缩短目录层级和过长的文件夹名称。

**Comment by rhwong** [comment]
未提供进一步反馈，问题关闭

**Comment by Arnolwutong** [comment]
感谢大佬，确实是文件目录层级太长了的问题，已经解决了，太感谢了。

**Comment by Arnolwutong** [comment]
> 尝试缩短目录层级和过长的文件夹名称。

感谢大佬，确实是文件目录层级太长了的问题，已经解决了，太感谢了
