### ISSUE TITLE
windows2012 登录错误

### ISSUE THREAD

**Issue by tts2** [rhwong/unidbg-fetch-qsign-onekey#22]
![QQ图片20230913004625](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/11350647/0797defc-331f-4a1a-ad1a-c7ee90774d99)
windows 2012 腾讯云 不知道什么错误

**Comment by rhwong** [comment]
看起来与qsign无关，建议更新go-cqhttp

**Comment by tts2** [comment]
这个用的您的最新版本，在我本机好使，在服务器上不行 报这个错

**Comment by rhwong** [comment]
我不太理解为什么protocol会访问198.18.0.28
这看起来是一个局域网IP
并且建议提供更加详细的日志，比如你在触发这个错我之前发生了什么

**Comment by rhwong** [comment]
go-cqhttp是[f16d72f](https://github.com/Mrs4s/go-cqhttp/actions/runs/6036458147)吗
如果不是建议更新到当前项目的最新版脚本，本项目当前最新版本为1.1.9-fix1

**Comment by rhwong** [comment]
长时间无反馈，问题关闭

**Comment by tts2** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/11350647/69370258-54ff-4779-ba98-4718ebbf1f1d)
这个是完整调用案例
