### ISSUE TITLE
持续报错后闪退

### ISSUE THREAD

**Issue by lufei19** [rhwong/unidbg-fetch-qsign-onekey#24]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/64579140/cbd940a1-5bd2-4ccc-85d9-13c1219b64b3)

**Comment by rhwong** [comment]
go-cqhttp问题不做处理

**Comment by rhwong** [comment]
建议更换[f16d72f](https://github.com/Mrs4s/go-cqhttp/actions/runs/6036458147)

**Comment by rhwong** [comment]
当前项目已经更新了go-cqhttp版本，配置文件也有变化。
建议下载release的1.1.9-fix1重新创建。

**Comment by lufei19** [comment]
> 当前项目已经更新了go-cqhttp版本，配置文件也有变化。 建议下载release的1.1.9-fix1重新创建。

![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/64579140/cf444f1b-945d-4e89-b89b-65f91fcfbe53)
使用1.1.9-fix1重新创建之后产生相同的报错，尚不清楚产生原因，不是每次运行一定出现 Windows Server 2012R2

**Comment by lufei19** [comment]
> 当前项目已经更新了go-cqhttp版本，配置文件也有变化。 建议下载release的1.1.9-fix1重新创建。

这个错误并不是一定发生的，但是一旦发生一般过一会就会闪退，然后登录次数多了就会code237登陆失败很烦

**Comment by rhwong** [comment]
那没有好的办法了。建议去go-cqhttp的issue进行反馈。

**Comment by rhwong** [comment]
判断为go-cqhttp问题，问题关闭。
