### ISSUE TITLE
报错后迅速闪退

### ISSUE THREAD

**Issue by lufei19** [rhwong/unidbg-fetch-qsign-onekey#25]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/64579140/a7b3bd75-1e88-4430-baec-256a7f28c839)
报错内容如图，由于报错后迅速闪退，我也不确定有没有别的报错

**Comment by rhwong** [comment]
根据你图里的内容，并没有发现报错。

**Comment by rhwong** [comment]
判断为go-cqhttp问题，问题关闭。
