### ISSUE TITLE
go cphttp重复提示 刷新token错误

### ISSUE THREAD

**Issue by zyx779455705** [rhwong/unidbg-fetch-qsign-onekey#27]
刷新 token 出现错误: code=-1, msg: QSign not initialized, unable to request_token, please submit the initialization package first.. server: http://127.0.0.1:13579

**Comment by mas-alone** [comment]
你是不是挂载了多个gocq实例，我遇到这个问题后重启qsign和gocq可以解决

**Comment by rhwong** [comment]
qsign没初始化，尝试重启所有进程

**Comment by 2838014063** [comment]
> qsign未初始化，尝试重启所有进程

大佬怎么初始化呢
