### ISSUE TITLE
window 2012 登录错误

### ISSUE THREAD

**Issue by tts2** [rhwong/unidbg-fetch-qsign-onekey#31]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/11350647/5419ee68-d80f-4b72-a9ff-a16f814d5790)
以上是完整登录日志,该怎么改下ip地址?

**Comment by tts2** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/11350647/56e720e6-5cee-4266-9294-a076cd6a79bf)

**Comment by rhwong** [comment]
签名仅支持Aphone、Apad，其他协议均不支持。
