### ISSUE TITLE
如何配置自动注册实例？

### ISSUE THREAD

**Issue by luluxiaoyu** [rhwong/unidbg-fetch-qsign-onekey#32]
版本：1.1.9
cq日志：2023/10/8 20:24:34WARNING自动注册实例已关闭，请配置 sign-server 端自动注册实例以保持正常签名
2023/10/8 20:24:34INFO从文件 data/versions/1.json 读取协议版本 Android Phone 8.9.73.11945.
2023/10/8 20:24:34INFO自动刷新 token 已关闭，token 过期后获取签名时将不会立即尝试刷新获取新 token
2023/10/8 20:24:34WARNING定时刷新 token 已关闭

**Comment by rhwong** [comment]
go-cqhttp端无需配置自动注册，因为qsign端已经配置过自动注册了
### 两者只能开一个
