### ISSUE TITLE
【bug】error报错

### ISSUE THREAD

**Issue by YouYouLip** [rhwong/unidbg-fetch-qsign-onekey#37]
环境：Windows 11
ICQQ 0.5.4
Qsign 1.1.9
txlib 8.9.80

运行时会一直出现以下error报错

[FEKit_]info: device_info.h:534 534
[FEKit_]info: device_info.h:536 536
[FEKit_]info: device_info.h:538 538
[FEKit_]info: device_token.h:276 begin pack
[FEKit_]info: device_token.h:278 pack buff result len:1412
[FEKit_]info: device_token.h:293 begin sendmessage : len :1412
[FEKit_]info: device_token.h:316 response len :0
[FEKit_]error: device_token.h:320 get token error! errorcode:907,mFailedTimes:5
[FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
FEBound.transform(22c4b4a4167801080001000102000100001e4617c08fa7a7cd1cf535594c3d1812000000004865726f) => ddc303386c3d01a85203b85708b8690dfc554bced81eab3adfce11a5153fadfeada752fda80deed54b
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:154 channel not ready
[FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
FEBound.transform(2660baa6e8b2a5940b0001080001000102000100006c8d09ea1db275249e3d3def000000004865726f) => d8770a3406acae845d0dbd510dbe6305fda755fda8e058a074c9f0f5c309adec9fa752fda80deed54b
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:154 channel not ready
[FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
FEBound.transform(460aee2783e6f6e7c44e70e44580ccabab030108000100010200010000a5a0eaa4000000004865726f) => 08a9c66e2284674ad1a85800b7184fa977ae55fba8570dae560dbd530dc3b3817ea752fda80deed54b
[FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:154 channel not ready
FEBound.transform(029c8b5b5beb0108000100010200010000a7b2ecbe80821300950e7c23e158b4c2000000004865726f) => fd8d3423308301a85203b85708b8690dfc38009fc912507d527ab6f2c6ae1bc2eda752fda80deed54b
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:154 channel not ready
[FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
-------------------------------------------------------------------------------
有时候也会有
[FEKit_]info: ChannelManager.cpp:121 origin cmd:O3GetTail ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:124 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:O3GetTail reason:0
[FEKit_]info: task_handle.h:77 TaskSystem not allow
[FEKit_]info: ChannelManager.cpp:121 origin cmd:GetSecConf ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:124 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:GetSecConf reason:0
[FEKit_]info: task_handle.h:77 TaskSystem not allow
Assertion failed: obj->ref > 0, file qom/object.c, line 707

然后qsign就停止运行了，大概每隔几个小时复现一次

**Comment by YouYouLip** [comment]
甚至还会出现未响应情况，qsign还在运行，但是已经不输出了，大佬怎么解决

**Comment by YouYouLip** [comment]
已反应给其他维护sign大佬，说是修复了但是我还没进行使用，大佬感兴趣可以去看一看跟进一下 是不是这个问题https://gitee.com/touchscale/Qsign/issues/I8815W?from=project-issue

**Comment by rhwong** [comment]
是1.2.1版本吗
