### ISSUE TITLE
遇到了看不懂的报错

### ISSUE THREAD

**Issue by qfwycn** [rhwong/unidbg-fetch-qsign-onekey#40]
![DL$EJMC@$(E%)W L MYIZKV](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/65634806/7f564dae-4837-46da-b588-5c043fb947c0)
![PBBE5AZD1D9(QYGVQ6Z(XRH](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/65634806/6d35f4eb-cd87-4f16-ac7e-3100c8c1928c)

**Comment by qfwycn** [comment]
最后的记录，然后qsign服务器就无响应了

**Comment by rhwong** [comment]
Qsign的核心已经停止技术支持了，没有人对其进行维护了。
如果是使用1.2.1版本出现问题，请换用最新的1.1.9-fix2
