### ISSUE TITLE
当前txlib/8.9.80/android_pad.json里面提供的app_id和sub_app_id有误

### ISSUE THREAD

**Issue by byx2020** [rhwong/unidbg-fetch-qsign-onekey#41]
截至2023年10月16日13:06:44，txlib8.9.80的android_phone.json和android_pad.json里面的app_id和sub_app_id都是相同的，
这会导致即便在gocq里面选择了android_pad协议登录，但最终登录的协议始终会是android_phone，希望能够修复。

**Comment by rhwong** [comment]
Fixed
