### ISSUE TITLE
1.1.6DEBUG

### ISSUE THREAD

**Issue by Nenot233** [rhwong/unidbg-fetch-qsign-onekey#6]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/108965579/946a97d2-b499-40e0-ade6-79bcffd736a9)
启动时候显示这个，是环境变量问题吗？
zulu19.32.13-ca-jdk19.0.2-win_x64

**Comment by rhwong** [comment]
这不是起来了吗。。
而且我给自带了jre了啊，不用你自己装java
