### ISSUE TITLE
请问大佬一键后出现这种问题怎么办？

### ISSUE THREAD

**Issue by SGTomokigod** [rhwong/unidbg-fetch-qsign-onekey#7]
按照步骤启动bat后出现如下图情况，小白实在搞不清楚是什么问题。。。
![11](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/96625664/5190f375-90ce-4166-a9fe-629ec186b531)
![22](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/96625664/27bdde88-41ed-461e-9e24-f4f3ad4f8c9e)
![33](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/96625664/544586a4-3e70-4ced-8648-fddf6cd8f3bd)

**Comment by SGTomokigod** [comment]
我只下载了release中的[qsign-onekey-1.1.0]文件，是否还需要运行其他工具？望大佬指教！

**Comment by rhwong** [comment]
没闪退就是正常，你直接用gocq对接一下试试。
另外不建议1.1.0，会封号。
由于go-cqhttp还未适配最新版，所以我没有给新版的qsign做release
你可以切换分支到[test-1.1.6](https://github.com/rhwong/unidbg-fetch-qsign-onekey/tree/test-1.1.6-go-cqhttp-x86)，然后直接download zip，而不是下载release。这个分支自带dev版本的go-cqhttp

**Comment by rhwong** [comment]
Close：时间太久
