### ISSUE TITLE
在win11电脑上无法启动

### ISSUE THREAD

**Issue by super1207** [rhwong/unidbg-fetch-qsign-onekey#9]
以下是我的操作步骤，不知道是不是我忽略了什么？用的是截至2023/7/31中午12点最新的main分支。
![第一步](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/30586004/1101a715-dd1b-4231-899d-7be75ab8c004)
![第二步](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/30586004/cc9c22f1-aa67-4df2-a4e1-bde45e6de74b)
![第三步](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/30586004/ce5e3b08-508a-4200-8551-b2d377619853)
![结果](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/30586004/1efe0bd6-26ba-465a-806c-0f3d370528c7)
![系统信息](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/30586004/46af3329-2e5e-477d-b1d2-d20ff7b6ab52)
![系统更新](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/30586004/8238042d-609d-4f43-b988-175e2787f67f)

**Comment by rhwong** [comment]
目前已确认在2022版本windows11内核的server版本系统运行不佳，与gocqhttp之间会无法通信。暂未收到关于win11直接无法运行的反馈，稍后我找人测试一下。

**Comment by KewenCode** [comment]
win10一样无法运行最新bat

**Comment by FanJZSS** [comment]
> 目前已确认在2022版本windows11内核的server版本系统运行不佳，与gocqhttp之间会无法通信。暂未收到关于win11直接无法运行的反馈，稍后我找人测试一下。

实测Win10 LTSC2021运行目前[main](https://github.com/rhwong/unidbg-fetch-qsign-onekey)最新1.1.7版本的Start_Qsign.bat后出现同样问题，使用[test-1.1.7](https://github.com/rhwong/unidbg-fetch-qsign-onekey/tree/test-1.1.7-go-cqhttp-x86)的Start_Qsign.bat则正常
![QQ截图20230731225715](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/96369018/74c11459-0dab-4a56-ac39-e5ce0843941c)

**Comment by rhwong** [comment]
已修复，写注释的时候写了中文导致的，由于编码格式被GitHub自己变了，所以乱码了（GitHub真是个老六我服了）

**Comment by rhwong** [comment]
最离谱的是写完了我这自己还能运行，你找谁说理去，烦死了。
提前转码上去就是乱码，不转码别人下载下来就不能用。
呕了

**Comment by FanJZSS** [comment]
> 已修复，写注释的时候写了中文导致的，由于编码格式被GitHub自己变了，所以乱码了（GitHub真是个老六我服了）

还有一个小问题（
现在最新[main](https://github.com/rhwong/unidbg-fetch-qsign-onekey)的`Start_Qsign.bat`确实可以正常启动了，但是无论是首次运行还是再次运行，都会有一句'else' 不是内部或外部命令，也不是可运行的程序或批处理文件。
[unidbg-fetch-qsign](https://github.com/fuqiuluo/unidbg-fetch-qsign)那边也有个小更新（逃
![QQ截图20230801010626](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/96369018/48d2a12f-5027-4ed3-ab39-05efc08d2708)

**Comment by rhwong** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/58497504/6206f949-14f8-4c19-8613-bf13d80e4ceb)
奇怪 木有啊
